# Generated by Django 4.2.3 on 2024-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='para_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
