# Generated by Django 4.2.3 on 2024-12-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_para_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='home_img',
            field=models.ImageField(default=0, upload_to='home_images/'),
            preserve_default=False,
        ),
    ]
