# Generated by Django 4.2.3 on 2023-12-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_icom', models.CharField(max_length=10)),
                ('menu_title', models.CharField(max_length=10)),
                ('menu_des', models.TextField(max_length=100)),
            ],
        ),
    ]
