# Generated by Django 4.2.3 on 2024-12-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_num', models.IntegerField()),
                ('aboutus_desc', models.TextField()),
            ],
        ),
    ]
