# Generated by Django 4.2.3 on 2024-12-27 05:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caboutus',
            name='aboutus_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
